name: Build ESP-IDF project
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:latest
    steps:
      - uses: actions/checkout@v4
      - uses: espressif/build-esp-idf-projects-action@v1
        with:
          idf_path: /opt/esp-idf
          target: esp32s3