name: Build ESP-IDF project
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
            submodules: 'recursive'

      - name: Build ESP-IDF project
        uses: espressif/esp-idf-ci-action@v1
        with:
            esp_idf_version: v6.0
            target: esp32s3
            extra_docker_args: -v ./.ccache:/root/.ccache -e CCACHE_DIR=/root/.ccache